/* Read-only validation. No npm dependencies. node validate_patch.js */
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=process.env.SPAT5_PATH||require('path').join(require('os').homedir(),'Documents/Max 9/Packages/spat5');
const maxroot='/Applications/Max.app/Contents/Resources/C74';
const patch=JSON.parse(fs.readFileSync('dot_area_spat_explorer.maxpat','utf8')).patcher;
const checks=[],errors=[],objectNames=new Set();let boxes=0,cords=0,views=0;
function check(label,fn){try{fn();checks.push(label);}catch(e){errors.push(label+': '+e.message);}}
function intersect(a,b,gap=0){return a[0]<b[0]+b[2]+gap&&a[0]+a[2]+gap>b[0]&&a[1]<b[1]+b[3]+gap&&a[1]+a[3]+gap>b[1];}
function validate(p,path){
 views++;const ids=new Set(),by={};
 for(const {box:b} of p.boxes){boxes++;assert(!ids.has(b.id),'duplicate '+b.id);ids.add(b.id);by[b.id]=b;assert(b.patching_rect.length===4);assert(b.patching_rect.every(Number.isFinite));assert(b.patching_rect[2]>0&&b.patching_rect[3]>0);const name=b.maxclass==='newobj'?b.text.split(' ')[0]:b.maxclass;objectNames.add(name);if(b.patcher)validate(b.patcher,path+'/'+b.id);}
 for(const mode of ['patching_rect','presentation_rect']){
  const list=p.boxes.map(x=>x.box).filter(b=>mode==='patching_rect'||b.presentation);
  for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++)assert(!intersect(list[i][mode],list[j][mode]),`${path} ${mode}: ${list[i].id} overlaps ${list[j].id}`);
  if(mode==='presentation_rect')for(const b of list){const [x,y,w,h]=b[mode];assert(x>=16&&y>=16&&x+w<=p.rect[2]-16&&y+h<=p.rect[3]-16,b.id+' outside presentation margin');}
 }
 for(const {patchline:l} of p.lines){cords++;const s=by[l.source[0]],d=by[l.destination[0]];assert(s&&d,'missing endpoint');assert(l.source[1]>=0&&l.source[1]<s.numoutlets,'invalid outlet '+s.id);assert(l.destination[1]>=0&&l.destination[1]<d.numinlets,'invalid inlet '+d.id);}
 // Directed patchcord graph must be acyclic, including control wiring.
 const done=new Set(),stack=new Set();function visit(id){assert(!stack.has(id),'feedback at '+id);if(done.has(id))return;stack.add(id);for(const {patchline:l} of p.lines)if(l.source[0]===id)visit(l.destination[0]);stack.delete(id);done.add(id);}if(path!=='main')for(const id of ids)visit(id);
}
check('JSON, recursive rectangles, margins, IDs, ports and acyclic audio subpatches',()=>validate(patch,'main'));
const ui={},emitted=[],missing=new Set();let diagram=[];
const byName=Object.fromEntries(patch.boxes.map(x=>[x.box.varname,x.box]));
const context={Math,post:()=>{},outlet:function(index,...args){const a=args.length===1&&Array.isArray(args[0])?args[0]:args;emitted.push([index,a]);},arrayfromargs:a=>Array.from(a),patcher:{getnamed:key=>{if(!byName[key]){missing.add(key);return null;}return {message:function(type,...args){if(key==='installation')diagram=args;else if(type==='set')ui[key]=args[0];}};}}};
vm.createContext(context);vm.runInContext(fs.readFileSync('dot_area_engine.js','utf8'),context);
function message(key,...args){context.messagename=key;context.anything(...args);}
function snapshot(){return JSON.parse(JSON.stringify({state:context.state,manual:context.manual,features:context.features,sources:context.sources,maps:context.maps}));}
check('Initial state is muted, gain zero, four sources, exact 4×3 scene coordinates',()=>{context.init();assert.equal(context.state.sound,0);assert.equal(context.state.gain,0);assert.equal(context.sources.length,4);assert(context.sources.every(v=>v.length===3&&v.every(Number.isFinite)));assert(emitted.some(([i,a])=>i===0&&a[0]==='bang'));assert.deepEqual(emitted.filter(x=>x[0]===3).at(-1)[1],[0]);});
check('Light rotation produces opposite centroid and updated source XYZ',()=>{message('azimuth',0);assert(Math.abs(context.features.cx)<1e-6);assert(context.features.cy<0);const a=snapshot();message('azimuth',90);assert(context.features.cx<0);assert(Math.abs(context.features.cy)<1e-6);assert.notDeepEqual(snapshot().sources,a.sources);});
check('Manual data survives mode switches; feature edit captures proxy',()=>{message('mode',0);message('area',0.19);const a=snapshot().manual;message('mode',1);message('azimuth',210);message('mode',0);assert.deepEqual(snapshot().manual,a);message('mode',1);const proxy=snapshot().features;message('area',0.7);assert.equal(context.state.mode,0);assert.equal(context.features.cx,proxy.cx);assert.equal(context.features.area,0.7);});
check('Copy proxy; AREA widens scene; mapping OFF restores zero spread',()=>{message('mode',1);const a=snapshot().features;message('copy');assert.equal(context.state.mode,0);assert.deepEqual(snapshot().manual,a);message('area',0);const narrow=snapshot().sources;message('area',1);assert.notDeepEqual(snapshot().sources,narrow);message('m1on',0);assert.equal(ui.m1out,'0.00 [base]');assert(context.sources.every(v=>Math.abs(v[0]-context.sources[0][0])<1e-6));});
check('Penumbra increases room; density distance override; entropy envelopment',()=>{message('penumbra',0);const dry=Number(ui.m2out);message('penumbra',1);assert(Number(ui.m2out)>dry);message('m3on',1);message('density',0);const near=Math.hypot(...context.sources[0]);message('density',1);assert(Math.hypot(...context.sources[0])>near);message('m5on',1);message('entropy',1);assert.equal(ui.m5out,'75.00');});
check('All seven mapping gates, inverted ranges and finite boundaries',()=>{for(let i=0;i<7;i++){message('m'+i+'on',1);let m=context.maps[i],lo=m.min,hi=m.max;message('m'+i+'min',hi);message('m'+i+'max',lo);message('m'+i+'on',0);assert(context.sources.every(v=>v.every(Number.isFinite)));}message('mode',0);message('cx',0);message('cy',0);message('cz',0);message('m0on',1);message('m0min',-2.5);message('m0max',2.5);assert(Math.hypot(...context.sources[0])>=0.3499);});
check('Presets preserve sound/gain; neutral, narrow, wide, edge, unstable',()=>{message('sound',1);message('gain',0.12);for(let i=0;i<5;i++){message('preset',i);assert.equal(context.state.sound,1);assert.equal(context.state.gain,0.12);assert.equal(context.state.resolution,1);assert(context.sources.every(v=>v.every(Number.isFinite)));}assert(context.state.orbit);const a=context.state.azimuth;context.tick();assert.notEqual(context.state.azimuth,a);message('panic');assert.equal(context.state.sound,0);assert.equal(context.state.orbit,0);});
check('Resolution mutes 3 voice gains; input bounds and frequency band limits',()=>{message('resolution',0);const start=emitted.length;message('frequency',99999);const values=emitted.slice(start).filter(([i,a])=>i===2);for(const [i,a] of values){if(/^f[1-4]$/.test(a[0]))assert(a[1]>=20&&a[1]<=12000);if(/^a[234]$/.test(a[0]))assert.equal(a[1],0);}message('gain',5);assert.equal(context.state.gain,1);});
check('All UI destinations exist and parameter updates use set (no UI feedback)',()=>assert.deepEqual([...missing],[]));
const references=['help/spat5.oper.maxhelp','help/spat5.pan~.maxhelp','help/spat5.spat~.maxhelp','help/spat5.viewer.embedded.maxhelp','examples/tutorials/spat5.tuto-basic-1.maxpat','examples/tutorials/spat5.tuto-binaural-1.maxpat','examples/tutorials/spat5.tuto-presets.maxpat','docs/ref/refpages/spat5-ref/spat5.oper.maxref.xml','docs/ref/refpages/spat5-ref/spat5.viewer.maxref.xml','docs/ref/refpages/spat5-ref/spat5.spat~.maxref.xml'];
references.push('help/spat5.virtualspeakers~.maxhelp','help/spat5.converter.maxhelp','help/spat5.osc.route.maxhelp','help/spat5.osc.ignore.maxhelp','help/spat5.osc.udpreceive.maxhelp','help/spat5.osc.udpsend.maxhelp','docs/ref/refpages/spat5-ref/spat5.virtualspeakers~.maxref.xml');
const referenceText=references.map(f=>fs.readFileSync(root+'/'+f,'utf8')).join('\n');
function normalize(p){return p.replace(/\/(source|speaker|room)\/(\d+|\*)\//g,'/$1/[index]/');}
const paths=[...new Set(emitted.filter(([i,a])=>i<=1&&String(a[0]).startsWith('/')).map(([i,a])=>a[0]))];
check('Every emitted Spat address occurs in installed XML/help/tutorial sources',()=>{for(const path of paths.filter(p=>!p.startsWith('/dotarea/'))){const normalized=normalize(path);assert(referenceText.includes(path)||referenceText.includes(normalized),'unverified OSC '+path);}});
check('All patch-embedded Spat addresses and initialization attributes verified',()=>{const strings=[];function walk(p){for(const {box:b} of p.boxes){if(b.text)strings.push(b.text);if(b.patcher)walk(b.patcher);}}walk(patch);for(const str of strings){if(!str.includes('spat5.')&&!(str.startsWith('/')&&str.length<150))continue;for(const path of str.match(/\/[A-Za-z][A-Za-z0-9_/*]*/g)||[]){if(path.startsWith('/dotarea/'))continue;const normalized=normalize(path);assert(referenceText.includes(path)||referenceText.includes(normalized),'unverified patch OSC '+path);}for(const attr of str.match(/@[a-z]+/g)||[])assert(referenceText.includes(attr),'unverified attribute '+attr);}});
check('Spat architecture and initialization match official binaural tutorial',()=>{const text=JSON.stringify(patch);assert(text.includes('@inputs 4 @outputs 2 @rooms 1 @internals 8'));assert(text.includes('/panning/type binaural'));assert(text.includes('/source/number 4'));assert(text.includes('line~ 0.'));assert(text.includes('clip~ -0.95 0.95'));assert(text.includes('@speakers 17'));assert(text.includes('@inputs 4 @outputs 17'));assert(!text.includes('dac~ 3'));});
check('Object names resolve to installed Max reference pages or Spat externals',()=>{for(const name of objectNames){if(name==='p')continue;const refName=({'*~':'times~','+~':'plus~','<~':'lessthan~','!-~':'rminus~'})[name]||name;const paths=[maxroot+'/docs/refpages/max-ref/'+refName+'.maxref.xml',maxroot+'/docs/refpages/msp-ref/'+refName+'.maxref.xml',root+'/externals/'+name+'.mxo'];assert(paths.some(fs.existsSync),'unresolved '+name);}});
check('Runtime paths are portable; no external media or browser DSP',()=>{for(const f of ['dot_area_spat_explorer.maxpat','dot_area_engine.js','dot_area_view.js']){const text=fs.readFileSync(f,'utf8');assert(!/\/Users\/|\/private\/tmp|https?:|sfplay~|buffer~|node\.script/.test(text),f);}for(const d of patch.dependency_cache||[])assert(fs.existsSync(d.name));});
check('Presentation controls maintain at least 6px clearance',()=>{const list=patch.boxes.map(x=>x.box).filter(x=>x.presentation);for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++)assert(!intersect(list[i].presentation_rect,list[j].presentation_rect,6),list[i].id+' / '+list[j].id+' too close');});
check('Every presentation object stays within its header, section or footer bounds',()=>{const sections=[[24,18,1432,74],[24,105,610,464],[670,105,786,302],[670,413,786,159],[24,615,866,429],[920,615,536,429],[24,1064,1432,70],[24,1163,1432,251]];for(const {box:b} of patch.boxes){if(!b.presentation)continue;const [x,y,w,h]=b.presentation_rect;assert(sections.some(([a,c,d,e])=>x>=a&&y>=c&&x+w<=a+d&&y+h<=c+e),b.id+' extends outside a section');}});
// Snapshot for an offline visual proof using exactly the real JS drawing code.
context.init();context.update();
const drawing=[],drawContext={box:{rect:[0,0,610,350]},arrayfromargs:a=>Array.from(a),outlet:function(...args){drawing.push(['outlet',...args]);},mgraphics:{}};
for(const k of ['init','redraw','set_source_rgba','set_line_width','move_to','line_to','stroke','ellipse','fill','select_font_face','set_font_size','show_text','rectangle','close_path'])drawContext.mgraphics[k]=(...a)=>drawing.push([k,...a]);
vm.createContext(drawContext);vm.runInContext(fs.readFileSync('dot_area_view.js','utf8'),drawContext);
check('Real jsui drawing and drag handler execute; light follows coordinates',()=>{drawContext.scene(...diagram);drawContext.paint();drawContext.onclick(305,50);const d=drawing.filter(x=>x[0]==='outlet').at(-1);assert.equal(d[2],'lightxy');assert(Math.abs(d[3])<1e-6);});
if(process.argv.includes('--preview')) process.stdout.write(JSON.stringify({ui,drawing,sourcePositions:context.sources})+'\n');
else {console.log(JSON.stringify({result:errors.length?'FAIL':'PASS',boxes,patchers:views,patchcords:cords,checks,errors,objectNames:[...objectNames].sort(),spatAddresses:paths.sort()},null,2));}
if(errors.length)process.exitCode=1;
